/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Wang zhilong",
  "description": "前端开发记录",
  "base": "/wzl_blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/wzl_blog/images/bg.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "前端",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "01.前端",
            "imgUrl": "/images/web.png",
            "description": "前端知识总结，以及问题记录"
          }
        },
        "title": "前端",
        "date": "2022-07-01T10:11:34.000Z",
        "permalink": "/frontEnd/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E5%89%8D%E7%AB%AF.html",
      "relativePath": "00.目录页/01.前端.md",
      "key": "v-dc05eefc",
      "path": "/frontEnd/"
    },
    {
      "title": "第二个",
      "frontmatter": {
        "title": "第二个",
        "date": "2022-07-01T10:13:33.000Z",
        "permalink": "/pages/cfb29a/",
        "categories": [
          "测试",
          "子分页A"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/01.%E7%9F%A5%E8%AF%86%E6%80%BB%E7%BB%93/02.%E7%AC%AC%E4%BA%8C%E4%B8%AA.html",
      "relativePath": "01.前端/01.知识总结/02.第二个.md",
      "key": "v-6d211532",
      "path": "/pages/cfb29a/",
      "headers": [
        {
          "level": 3,
          "title": "前端知识梳理",
          "slug": "前端知识梳理"
        },
        {
          "level": 4,
          "title": "js数据类型",
          "slug": "js数据类型"
        },
        {
          "level": 4,
          "title": "字符串截取",
          "slug": "字符串截取"
        },
        {
          "level": 4,
          "title": "浏览器存储",
          "slug": "浏览器存储"
        },
        {
          "level": 4,
          "title": "for in和for of",
          "slug": "for-in和for-of"
        },
        {
          "level": 4,
          "title": "获取对象的key",
          "slug": "获取对象的key"
        },
        {
          "level": 4,
          "title": "改变函数的this指向",
          "slug": "改变函数的this指向"
        },
        {
          "level": 4,
          "title": "重绘和回流",
          "slug": "重绘和回流"
        },
        {
          "level": 4,
          "title": "Get和Post请求",
          "slug": "get和post请求"
        },
        {
          "level": 4,
          "title": "获取时间戳的方法",
          "slug": "获取时间戳的方法"
        },
        {
          "level": 4,
          "title": "防抖和节流",
          "slug": "防抖和节流"
        },
        {
          "level": 4,
          "title": "title和alt属性",
          "slug": "title和alt属性"
        },
        {
          "level": 4,
          "title": "css权重优先级",
          "slug": "css权重优先级"
        },
        {
          "level": 4,
          "title": "Set和Map数据结构",
          "slug": "set和map数据结构"
        },
        {
          "level": 4,
          "title": "Array.from()使用",
          "slug": "array-from-使用"
        }
      ]
    },
    {
      "title": "git命令",
      "frontmatter": {
        "title": "git命令",
        "date": "2022-07-01T10:13:19.000Z",
        "permalink": "/pages/1a89bc/",
        "categories": [
          "知识总结"
        ],
        "tags": [
          null
        ],
        "sticky": 1
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/01.%E7%9F%A5%E8%AF%86%E6%80%BB%E7%BB%93/01.git%E6%93%8D%E4%BD%9C.html",
      "relativePath": "01.前端/01.知识总结/01.git操作.md",
      "key": "v-1c32e20c",
      "path": "/pages/1a89bc/",
      "headers": [
        {
          "level": 4,
          "title": "1.git提交命令",
          "slug": "_1-git提交命令"
        },
        {
          "level": 4,
          "title": "2.git分支操作",
          "slug": "_2-git分支操作"
        },
        {
          "level": 4,
          "title": "3.git撤销命令",
          "slug": "_3-git撤销命令"
        },
        {
          "level": 4,
          "title": "4.git暂存操作",
          "slug": "_4-git暂存操作"
        },
        {
          "level": 4,
          "title": "5.git差异比较",
          "slug": "_5-git差异比较"
        }
      ]
    },
    {
      "title": "第二个",
      "frontmatter": {
        "title": "第二个",
        "date": "2022-07-01T10:14:06.000Z",
        "permalink": "/pages/f2ec99/",
        "categories": [
          "测试",
          "子分页B"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/02.%E9%97%AE%E9%A2%98%E8%AE%B0%E5%BD%95/02.%E7%AC%AC%E4%BA%8C%E4%B8%AA.html",
      "relativePath": "01.前端/02.问题记录/02.第二个.md",
      "key": "v-02c059d6",
      "path": "/pages/f2ec99/"
    },
    {
      "title": "待定",
      "frontmatter": {
        "title": "待定",
        "date": "2022-07-01T14:43:13.000Z",
        "permalink": "/pages/7054e9/",
        "categories": [
          "html"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.%E9%A1%B5%E9%9D%A2/01.html/01.%E5%BE%85%E5%AE%9A.html",
      "relativePath": "02.页面/01.html/01.待定.md",
      "key": "v-35b0d28e",
      "path": "/pages/7054e9/",
      "excerpt": "<p><img src=\"/images/banner.png\" alt=\"Dark\"></p>\n"
    },
    {
      "title": "第一个",
      "frontmatter": {
        "title": "第一个",
        "date": "2022-07-01T10:13:57.000Z",
        "permalink": "/pages/ecc339/",
        "categories": [
          "测试",
          "子分页B"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/02.%E9%97%AE%E9%A2%98%E8%AE%B0%E5%BD%95/01.%E7%AC%AC%E4%B8%80%E4%B8%AA.html",
      "relativePath": "01.前端/02.问题记录/01.第一个.md",
      "key": "v-38b6b73e",
      "path": "/pages/ecc339/"
    },
    {
      "title": "待定",
      "frontmatter": {
        "title": "待定",
        "date": "2022-07-01T14:43:40.000Z",
        "permalink": "/pages/0c1bb9/",
        "categories": [
          "css"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.%E9%A1%B5%E9%9D%A2/02.css/01.%E5%BE%85%E5%AE%9A.html",
      "relativePath": "02.页面/02.css/01.待定.md",
      "key": "v-332ea080",
      "path": "/pages/0c1bb9/"
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-1ca87a40",
      "path": "/archives/"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-0a9fb360",
      "path": "/tags/"
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-4ace98c0",
      "path": "/categories/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-bb0e1570",
      "path": "/"
    }
  ],
  "themeConfig": {
    "blogger": {
      "avatar": "/images/avatar.jpg",
      "name": "汪志龙",
      "slogan": "行到水穷处，坐看云起时"
    },
    "logo": "/images/banner.png",
    "bodyBgImg": "/images/bg.jpg",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/frontEnd/",
        "items": [
          {
            "text": "知识总结",
            "link": "/pages/1a89bc/"
          },
          {
            "text": "问题记录",
            "link": "/pages/ecc339/"
          }
        ]
      },
      {
        "text": "页面",
        "items": [
          {
            "text": "html",
            "link": "/pages/7054e9/"
          },
          {
            "text": "css",
            "link": "/pages/0c1bb9/"
          }
        ]
      },
      {
        "text": "微博",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": {
      "/00.目录页/": [
        [
          "01.前端.md",
          "前端",
          "/frontEnd/"
        ]
      ],
      "catalogue": {
        "前端": "/frontEnd/"
      },
      "/01.前端/": [
        {
          "title": "知识总结",
          "collapsable": true,
          "children": [
            [
              "01.知识总结/01.git操作.md",
              "git命令",
              "/pages/1a89bc/"
            ],
            [
              "01.知识总结/02.第二个.md",
              "第二个",
              "/pages/cfb29a/"
            ]
          ]
        },
        {
          "title": "问题记录",
          "collapsable": true,
          "children": [
            [
              "02.问题记录/01.第一个.md",
              "第一个",
              "/pages/ecc339/"
            ],
            [
              "02.问题记录/02.第二个.md",
              "第二个",
              "/pages/f2ec99/"
            ]
          ]
        }
      ],
      "/02.页面/": [
        {
          "title": "html",
          "collapsable": true,
          "children": [
            [
              "01.html/01.待定.md",
              "待定",
              "/pages/7054e9/"
            ]
          ]
        },
        {
          "title": "css",
          "collapsable": true,
          "children": [
            [
              "02.css/01.待定.md",
              "待定",
              "/pages/0c1bb9/"
            ]
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "footer": {
      "createYear": 2022
    }
  }
}